name: fx
version: 30.0.0-7
summary: Terminal JSON viewer
description: Terminal JSON viewer
base: core20
grade: stable
confinement: strict
architectures:
  - build-on: armhf
  - build-on: amd64
  - build-on: arm64

apps:
  fx:
    command: fx
    plugs: [home, network]

parts:
  fx:
    plugin: go
    go-channel: 1.18/stable
    source: .
    source-type: git
    go-importpath: github.com/antonmedv/fx
    stage-snaps:
      - node/18/stable
    stage-packages:
      - libc6
      - libgcc1
