name: fx
version: 30.0.0-9
summary: Terminal JSON viewer
description: Terminal JSON viewer
base: core20
grade: stable
confinement: strict
architectures:
  - build-on: armhf
  - build-on: amd64
  - build-on: arm64

plugs:
  home:
    interface: personal-files
    read:
      - $HOME/.fxrc.js
  network:
    interface: network

apps:
  fx:
    command: bin/fx
    plugs: [ home, network ]

parts:
  fx:
    plugin: go
    source: https://github.com/antonmedv/fx.git
    source-type: git
    stage-snaps:
      - node/18/stable
